# Generated by Django 4.2.3 on 2023-07-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('affilation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('activity_type', models.CharField(max_length=10)),
                ('activity_name', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=10)),
                ('pass_fail', models.CharField(max_length=5)),
                ('fee', models.CharField(max_length=10)),
                ('sponsor', models.CharField(max_length=10)),
            ],
        ),
    ]
