# Generated by Django 4.2.3 on 2023-08-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='activity_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='activity_type',
            field=models.CharField(max_length=15),
        ),
    ]
