# Generated by Django 4.2.3 on 2023-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
